-- Generado por scripts/generar-seed.js desde public/js/data.js. No editar a mano.
begin;

insert into public.fuentes (clave, titulo, url) values
  ('sicMarcas', 'SIC · Marcas', 'https://sedeelectronica.sic.gov.co/temas/propiedad-industrial/marcas'),
  ('sicTarifas', 'SIC · Tarifas 2026 (Res. 77243/2025)', 'https://sedeelectronica.sic.gov.co/transparencia/normativa/resolucion-no-77243-del-30-de-septiembre-del-2025'),
  ('rues', 'RUES', 'https://www.rues.org.co'),
  ('imperiumlabs', 'imperiumlabs.co (estudio de videojuegos)', 'https://imperiumlabs.co/'),
  ('gSender', 'Google · Directrices para remitentes', 'https://support.google.com/a/answer/81126?hl=es'),
  ('hubspotIcp', 'HubSpot · Plantilla de ICP', 'https://www.hubspot.com/make-my-persona/ideal-customer-profile-template'),
  ('hubspotCac', 'HubSpot · Cálculo de CAC', 'https://www.hubspot.com/startups/sales-and-marketing/calculating-cac-for-startups'),
  ('clutch', 'Clutch · Precios de diseño web', 'https://clutch.co/web-designers/pricing'),
  ('verjel', 'Precios web en Colombia (blog de proveedor)', 'https://www.alejandroverjel.com/blog/diseno/cuanto-cuesta-pagina-web-colombia/'),
  ('pivoti', 'Precios web en Bogotá (blog de proveedor)', 'https://www.pivotilabs.com/blog/cuanto-cuesta-pagina-web-bogota'),
  ('enns', 'Pricing Creativity (resumen)', 'https://www.peterkang.com/lessons-from-pricing-creativity-by-blair-enns/'),
  ('dyf', 'Cobrar el diagnóstico (Double Your Freelancing)', 'https://doubleyourfreelancing.com/how-to-get-paid-for-project-discovery/'),
  ('dianRst', 'DIAN · Régimen Simple', 'https://micrositios.dian.gov.co/regimen-simple-tributacion/quienes-pueden-optar-por-el-simple/'),
  ('dian977', 'DIAN · Concepto 977/2023 (tarifas RST)', 'https://normograma.dian.gov.co/dian/compilacion/docs/oficio_dian_0977_2023.htm'),
  ('dianCiiu', 'DIAN · Resolución 114/2020 (CIIU)', 'https://normograma.dian.gov.co/dian/compilacion/docs/resolucion_dian_0114_2020.htm'),
  ('dianFe', 'DIAN · Requisitos de facturador electrónico', 'https://micrositios.dian.gov.co/sistema-de-facturacion-electronica/requerimientos-para-ser-facturador-electronico/'),
  ('ccbLey1780', 'CCB · Ley de Emprendimiento Juvenil', 'https://www.ccb.org.co/es/tramites-y-consultas/sobre-registros/normativas-registros-publicos/normativas-registros-publicos/ley-de-emprendimiento-juvenil'),
  ('ley1258', 'Ley 1258 de 2008 (SAS)', 'https://normas.cra.gov.co/gestor/docs/ley_1258_2008.htm'),
  ('rm01', 'CCB · Guía RM01 para SAS', 'https://assets.ctfassets.net/n1ptkpqt763u/2qPY8BkR0Awl2GgbTeQQri/1ed118cb5a6cf3ba9a9f61099d53ac81/GuiaRM_01.pdf'),
  ('sasVirtual', 'CCB · SAS virtual', 'https://www.ccb.org.co/es/servicios/crea-tu-empresa/constituye-tu-empresa/constitucion-virtual-sas'),
  ('vue', 'Ventanilla Única Empresarial', 'https://www.vue.gov.co/'),
  ('ccbTarifas', 'CCB · Tarifas 2026', 'https://assets.ctfassets.net/n1ptkpqt763u/3Y8yhxlVbzjMyD7njbElNL/a4bfae899c2186d803ec833699eb192c/Tarifas_Registros_Publicos_2026_y_afiliados.pdf'),
  ('rnbd', 'SIC · Quién debe inscribirse en el RNBD', 'https://sedeelectronica.sic.gov.co/publicaciones/boletin-juridico/concepto/cuales-personas-estan-obligadas-realizar-el-registro-de-bases-de-datos-personales-en-el-rnbd'),
  ('sicCorp', 'SIC · Datos corporativos y Ley 1581', 'https://sedeelectronica.sic.gov.co/boletin-juridico/conceptos/ambito-de-aplicacion-de-la-ley-1581-de-2012-en-datos-corporativos'),
  ('wheeler', 'Alina Wheeler · fases de identidad', 'https://logogeek.uk/podcast/design-a-brand-identity-with-alina-wheeler/'),
  ('ixdf', 'IxDF · Qué lleva un manual de marca', 'https://ixdf.org/literature/topics/brand-guidelines'),
  ('wcag', 'W3C · WCAG 2.2', 'https://www.w3.org/TR/WCAG22/'),
  ('vitals', 'web.dev · Core Web Vitals', 'https://web.dev/articles/vitals'),
  ('owaspH', 'OWASP · Cabeceras HTTP', 'https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html'),
  ('owasp10', 'OWASP Top 10:2025', 'https://top10.owasp.org/2025/'),
  ('gSchema', 'Google · Datos estructurados', 'https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data'),
  ('gSitemap', 'Google · Sitemaps', 'https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview'),
  ('gAi', 'Google · Contenido hecho con IA', 'https://developers.google.com/search/docs/fundamentals/using-gen-ai-content'),
  ('gbp', 'Google · Directrices del Perfil de Empresa', 'https://support.google.com/business/answer/3038177?hl=es'),
  ('hubspot', 'HubSpot · Precios CRM', 'https://www.hubspot.com/pricing/crm'),
  ('odoo', 'Odoo · Precios', 'https://www.odoo.com/pricing-plan'),
  ('odooCo', 'Odoo · Localización Colombia', 'https://www.odoo.com/documentation/19.0/es/applications/finance/fiscal_localizations/colombia.html'),
  ('n8n', 'n8n · Precios', 'https://n8n.io/pricing/'),
  ('n8nLic', 'n8n · Licencia (qué se puede vender)', 'https://docs.n8n.io/n8n-community-license/community-license/license-faq'),
  ('make', 'Make · Precios', 'https://www.make.com/en/pricing'),
  ('wompi', 'Wompi · Tarifas', 'https://wompi.com/es/co/planes-tarifas/plan-avanzado-agregador'),
  ('bold', 'Bold · Tarifas', 'https://bold.co/tarifas'),
  ('ruesDb', 'Bases de datos del RUES', 'https://www.camaramedellin.com.co/quiero-un-servicio-para-mi-empresa/informacion-estudios-y-bases-de-datos/bases-de-datos-de-empresas-registradas-en-el-registro-unico-empresarial-y-social-rues'),
  ('mapsTos', 'Google Maps Platform · Términos', 'https://cloud.google.com/maps-platform/terms'),
  ('close', 'Close · Plantillas de correo en frío', 'https://close.com/blog/cold-email-templates'),
  ('saleshandy', 'Saleshandy · Estructuras de correo', 'https://www.saleshandy.com/blog/cold-email-frameworks/'),
  ('lemlist', 'Lemlist · Correo en frío', 'https://www.lemlist.com/blog/cold-emailing'),
  ('ley2300', 'Ley 2300 de 2023', 'https://normograma.com/documentospdf/PruebaMintic/docs/ley_2300_2023.htm'),
  ('waPolicy', 'Política de WhatsApp Business', 'https://whatsappbusiness.com/policy/'),
  ('ross', 'Predictable Revenue (notas)', 'https://grahammann.net/book-notes/predictable-revenue-aaron-ross-marylou-tyler'),
  ('hootsuite', 'Hootsuite · Frecuencia por red', 'https://blog.hootsuite.com/how-often-to-post-on-social-media/'),
  ('hootIg', 'Hootsuite · Algoritmo de Instagram', 'https://blog.hootsuite.com/instagram-algorithm/'),
  ('ctwa', 'Meta · Anuncios clic a WhatsApp', 'https://developers.facebook.com/documentation/ads-commerce/marketing-api/ad-creative/messaging-ads/click-to-whatsapp'),
  ('waPricing', 'Meta · Precios de WhatsApp', 'https://developers.facebook.com/docs/whatsapp/pricing/'),
  ('sparktoro', 'SparkToro · Encuesta a agencias', 'https://sparktoro.com/blog/digital-agency-new-business-still-a-concern-referrals-still-rule-for-lead-gen-and-are-sales-pipelines-finally-recovering/'),
  ('effichat', 'Effichat', 'https://effichat.efficommerce.com/'),
  ('ruta', 'CCB · Ruta Bogotá Cundinamarca Emprende', 'https://www.ccb.org.co/es/servicios/crea-tu-empresa/preparate-para-crear-tu-empresa/ruta-emprender'),
  ('plan', 'Investigación estratégica (doc)', 'https://claude.ai/code/artifact/bb50d6fe-b609-4569-80c1-aa2c94769533')
on conflict (clave) do update set titulo = excluded.titulo, url = excluded.url;

insert into public.fases (id, numero, nombre, criterio_salida, orden) values
  ('f0', 'Fase 0', 'Validar', 'El nombre se puede registrar y las 7 decisiones están tomadas', 0),
  ('f1', 'Fase 1', 'Formalizar', 'NIT activo y primera factura electrónica emitida', 1),
  ('f2', 'Fase 2', 'Marca', 'Manual de marca v2 aprobado por ambas', 2),
  ('f3', 'Fase 3', 'Plataforma propia', 'imperiumlab.co pasa su propia Acta de calidad', 3),
  ('f4', 'Fase 4', 'Captación', 'Revisión del embudo con datos de 3 lotes', 4)
on conflict (id) do update set numero = excluded.numero, nombre = excluded.nombre, criterio_salida = excluded.criterio_salida, orden = excluded.orden;

update public.tareas set orden = orden + 10000;
insert into public.tareas (id, fase_id, responsable, horas, es_hito, titulo, porque, pasos, entregable, criterio_hecho, orden) values
  ('T01', 'f0', 'MJ', 2, true, 'Verificar que «Imperium Lab» se puede registrar como marca', 'El dominio ya es suyo, pero un dominio no da derechos de marca. Existe un estudio de videojuegos llamado Imperium Labs con un dominio casi igual.', array['Entra a la sede electrónica de la SIC → Propiedad industrial → Marcas y busca IMPERIUM, IMPERIUM LAB, IMPERIUMLAB e IMPERIUM LABS.', 'Revisa los resultados en las clases de Niza 42 (desarrollo de software), 9 (software descargable) y 35 (publicidad y gestión).', 'Anota cada resultado parecido en una tabla: signo, titular, clase y estado (vigente, en trámite, negada).', 'Busca «Imperium» en el RUES para ver si alguna sociedad colombiana ya usa el nombre.', 'Abre imperiumlabs.co y anota su sector y si opera en Colombia.', 'Si queda alguna duda, paga la búsqueda oficial de antecedentes de la SIC: COP 29.500 por signo en línea.', 'Escribe la conclusión en 5 líneas con semáforo: verde (seguir), amarillo (ajustar diseño o nombre), rojo (cambiar).']::text[], 'Informe de antecedentes de 1 página con semáforo.', 'Las dos leyeron el informe y el semáforo está en verde, o hay un plan B acordado.', 0),
  ('T02', 'f0', 'JQ', 1, false, 'Reservar @imperiumlab en las redes', 'Asegurar el mismo usuario en todas las redes antes de anunciar el nombre.', array['Revisa si @imperiumlab está libre en Instagram, TikTok, Facebook y LinkedIn.', 'Si no está libre en alguna, elige una sola variante para todas (por ejemplo @imperiumlab.co).', 'Crea las cuentas como cuentas de empresa o profesionales.', 'Activa la verificación en dos pasos en las cuatro.', 'Guarda los accesos en un gestor de contraseñas compartido entre las dos.', 'No publiques todavía: deja solo el nombre y una imagen provisional.']::text[], 'Lista de cuentas con usuario, correo de registro y responsable.', 'Las cuatro cuentas existen con el mismo usuario y con 2FA activa.', 1),
  ('T20', 'f2', 'JQ', 2, false, 'Auditar el manual de marca actual', 'El manual habla de Imperial Tech, de herramientas no-code y de IA al centro. El nuevo diferenciador es la web hecha con buenas prácticas verificables.', array['Lista todo lo que dice «Imperial Tech» o «soyimperialtech.com» y debe pasar a «Imperium Lab» e «imperiumlab.co».', 'Marca las contradicciones con el diferenciador: el pilar 2 dice «herramientas no-code» y la promesa pone la IA al centro.', 'Compara la misión («micronegocios que no pueden pagar una agencia») con la vertical y los precios que se van a decidir.', 'Revisa el contraste de la paleta (pestaña Marca): violeta con texto blanco da 4,36:1 y naranja con texto blanco 2,84:1. Ninguno pasa WCAG AA para texto normal.', 'Anota lo que falta: versiones del logo, área de respeto, tamaño mínimo, usos incorrectos, tipografías con nombre, iconografía, fotografía y aplicaciones.', 'Decide qué se conserva: la corona de tres formas y la «I» central siguen funcionando para Imperium.', 'Entrega una lista de cambios ordenada por prioridad.']::text[], 'Lista priorizada de cambios del manual.', 'MJ leyó la lista y no tiene objeciones.', 2),
  ('T03', 'f0', 'MJ', 2, false, 'Correo @imperiumlab.co en Google Workspace con SPF, DKIM y DMARC', 'Ya tienen los correos en Google. El dominio nuevo debe enviar correo confiable antes de cualquier prospección.', array['En admin.google.com agrega imperiumlab.co como dominio (alias o secundario, según cómo esté configurada hoy la cuenta).', 'Verifica el dominio con el registro TXT que da Google, en el panel DNS del proveedor donde compraron el dominio.', 'Configura los registros MX que indica Google y prueba enviar y recibir.', 'Publica el SPF: un solo TXT en la raíz con «v=spf1 include:_spf.google.com ~all». Si ya existe uno, combínalos.', 'Activa DKIM: Apps → Google Workspace → Gmail → Autenticar correo electrónico. Genera la clave, publica el TXT y pulsa «Iniciar autenticación».', 'Publica DMARC en _dmarc.imperiumlab.co: «v=DMARC1; p=none; rua=mailto:<correo de reportes>».', 'Envía un correo a una cuenta Gmail externa, abre «Mostrar original» y confirma SPF, DKIM y DMARC en PASS.', 'Crea hola@imperiumlab.co y una dirección por socia, con firma provisional.']::text[], 'Correos funcionando y captura de «Mostrar original» con los tres PASS.', 'SPF, DKIM y DMARC en PASS y las dos envían desde @imperiumlab.co.', 3),
  ('T04', 'f0', 'JQ', 2, false, 'Elegir la vertical inicial y escribir el ICP', 'Especializarse en un tipo de cliente baja la competencia por precio y hace que cada caso sirva para el siguiente.', array['Lista 3 verticales candidatas: distribuidoras y mayoristas que venden por WhatsApp, comercios con catálogo y servicios con citas.', 'Califica cada una de 1 a 5 en: dolor visible, capacidad de pago, facilidad para llegarles y caso propio (Estancoficial).', 'Elige la de mayor puntaje.', 'Escribe el ICP en 1 página con los 6 criterios de HubSpot: industria, presupuesto, urgencia, potencial, tamaño y ubicación.', 'Agrega señales que se vean desde afuera: web lenta o inexistente, pedidos por WhatsApp a mano, catálogo en PDF.', 'Define quién decide la compra y qué le duele.', 'Anota en qué se diferencia del público del manual actual (emprendedores y micronegocios) para la sesión de decisiones.']::text[], 'ICP de 1 página.', 'El ICP permite decir sí o no a un prospecto en menos de un minuto.', 4),
  ('T06', 'f0', 'MJ', 2, false, 'Costeo y punto de equilibrio', 'Los precios nuevos necesitan un piso: lo mínimo que se puede cobrar sin perder plata.', array['Lista los costos fijos mensuales: Google Workspace, dominio, hosting, herramientas (CRM, n8n), contador y cuenta bancaria.', 'Lista los costos variables por proyecto: hosting del cliente, comisiones de pasarela y licencias.', 'Estima las horas reales que tomó Estancoficial, por tipo de tarea.', 'Calcula el costo por hora objetivo: ingreso mensual deseado por socia dividido por las horas facturables.', 'Calcula el precio mínimo de cada paquete con un margen definido.', 'Calcula cuántos proyectos al mes cubren los costos fijos.', 'Comparte la hoja con JQ antes de la sesión de precios.']::text[], 'Hoja de costeo con precio mínimo por paquete.', 'JQ puede usar la hoja para fijar precios sin preguntar nada.', 5),
  ('T05', 'f0', 'JQ', 2, false, 'Rediseñar los precios en tres opciones y un diagnóstico pagado', 'Tres opciones hacen que el cliente elija cuál y no si compra. El diagnóstico pagado filtra prospectos y paga la preventa.', array['Usa el costeo de MJ como piso.', 'Define 3 paquetes (por ejemplo Esencial, Crecimiento y A la medida) con alcance, plazo y garantía.', 'Define el diagnóstico pagado: auditoría de web y WhatsApp con informe, y si se descuenta del proyecto.', 'Define qué incluye cada plan de soporte (hoy COP 80.000, 150.000 y 200.000 al mes).', 'Compara con referencias: web corporativa COP 2,5 a 6 millones y sitio de 5 a 8 páginas en Bogotá COP 5 a 9 millones, según blogs de proveedores sin metodología.', 'Decide dónde quedan frente al «punto medio inteligente» del manual.', 'Escribe la tabla de precios de 1 página para la web y las propuestas.']::text[], 'Tabla de precios v1.', 'Precios aprobados por las dos en la sesión de decisiones.', 6),
  ('T07', 'f0', 'AMBAS', 1, true, 'Sesión de decisiones de arranque', 'Siete decisiones frenan todo lo demás. Se toman juntas, una vez, y quedan escritas.', array['Nombre: ¿seguimos con Imperium Lab según el semáforo de T01?', 'Vertical inicial (según T04).', 'SAS virtual con estatutos estándar o constitución tradicional con estatutos propios.', 'Régimen Simple u ordinario: queda pendiente de la reunión con el contador.', 'CRM: Odoo todo en uno, o HubSpot Free más un software de facturación.', 'Precios en tres opciones (según T05).', 'Posicionamiento: el manual dice «democratizar, no-code»; el plan dice «buenas prácticas verificables». Elegir uno y escribirlo en una frase.', 'Definir quién será la representante legal y quién la suplente.', 'Escribir las decisiones en las notas de esta tarea.']::text[], 'Acta de decisiones en las notas de la tarea.', 'Las 7 decisiones están escritas y las dos están de acuerdo.', 7),
  ('T08', 'f1', 'MJ', 2, false, 'Reunión con contador: régimen, CIIU e ICA', 'La decisión tributaria cambia el RUT, las tarifas y lo que se cobra al cliente.', array['Prepara las preguntas antes de la reunión.', 'Régimen Simple u ordinario. El RST para servicios profesionales arranca en 5,9% hasta 6.000 UVT; confirmar en qué grupo cae el desarrollo de software.', 'CIIU principal 6201 y secundarios 6202, 6311 o 6312.', 'ICA en Bogotá: tarifa por CIIU y fechas de declaración.', 'Capital suscrito y pagado sugerido.', 'Si aplica el beneficio de la Ley 1780 (socias de 18 a 35 años) y si sigue vigente en 2026.', 'Obligaciones mensuales (retenciones, IVA si aplica, facturación) y honorarios del contador.', 'Escribe las respuestas en las notas de la tarea.']::text[], 'Respuestas del contador por escrito.', 'Saben qué régimen elegir en el RUT y qué CIIU registrar.', 8),
  ('T21', 'f2', 'JQ', 2, false, 'Brief de marca Imperium Lab', 'El logo y el manual salen de la estrategia, no al revés.', array['Propósito en una frase.', 'Para quién: resumen del ICP.', 'Promesa nueva que incluya el Acta de calidad.', 'Tres pilares reescritos. Sugerencia: hecho a mano con estándares verificables; un negocio que funciona solo (web, WhatsApp y automatización); acompañamiento en lenguaje claro.', 'Qué significa «Lab»: un taller donde se prueba y se mide.', 'Tono: decidan entre tú y usted. El manual menciona «vos», que es poco común en Bogotá; evalúen si conecta con su público.', 'Tres palabras que sí son la marca y tres que no.', 'Valida el brief con MJ.']::text[], 'Brief de marca de 1 página.', 'Las dos firman el brief.', 9),
  ('T09', 'f1', 'MJ', 4, false, 'Estatutos y acuerdo entre socias', 'Deja escrito cómo se decide, cómo se reparte y qué pasa si una socia sale.', array['Según la decisión de T07: SAS virtual (estatutos estándar no editables) o tradicional (estatutos propios).', 'Razón social: IMPERIUM LAB S.A.S. Verifica homonimia en el RUES.', 'Objeto social amplio: desarrollo de software, consultoría, automatización y marketing digital.', 'Capital autorizado, suscrito y pagado según el contador.', 'Reparto de acciones (por ejemplo 50/50) y representante legal con suplente.', 'Reglas de decisión, salida de una socia y propiedad intelectual del código a nombre de la SAS.', 'Si van por SAS virtual, escribe el acuerdo entre socias como documento privado aparte.']::text[], 'Borrador de estatutos o acuerdo entre socias.', 'Borrador listo para revisión de JQ.', 10),
  ('T22', 'f2', 'JQ', 4, false, 'Rediseñar el logo: exploración de 3 rutas', 'El logo actual es una corona de tres formas que giran con una «I» al centro. Hay que adaptarlo al nombre nuevo y hacerlo legible en tamaños pequeños.', array['Revisa el logo actual y decide qué se conserva: la corona, las tres formas y la «I» de Imperium.', 'Regla: el símbolo debe leerse a 16 px (favicon) y dentro de un avatar circular.', 'Ruta A: evolución del símbolo actual con el nuevo wordmark «Imperium Lab».', 'Ruta B: símbolo simplificado, con menos piezas y sin depender del degradado.', 'Ruta C: monograma «IL» o «I» con la idea de laboratorio.', 'Prueba el wordmark con 2 o 3 tipografías sans gruesas de Google Fonts (licencia libre).', 'Muestra cada ruta en positivo, en negativo sobre #0D0D12 y en un solo color.', 'Arma en Figma una lámina que compare las tres rutas.']::text[], 'Lámina con 3 rutas de logo.', 'Las 3 rutas se ven bien a 16 px, 48 px y 300 px.', 11),
  ('T10', 'f1', 'JQ', 1, false, 'Revisar y aprobar los estatutos', 'Los estatutos los firman las dos.', array['Lee el borrador completo.', 'Deja comentarios en el documento.', 'Acuerden los cambios en una llamada corta.', 'Aprueba la versión final.']::text[], 'Estatutos aprobados.', 'Versión final sin comentarios abiertos.', 12),
  ('T23', 'f2', 'AMBAS', 1, false, 'Elegir la ruta de logo y validarla con 3 personas', 'Una prueba rápida con el público evita elegir solo por gusto.', array['Cada una califica las 3 rutas: legible en pequeño, fácil de recordar y coherente con la promesa.', 'Elijan una.', 'Muéstrenla a 3 personas del público (por ejemplo Estancoficial y dos prospectos).', 'Hagan una sola pregunta: ¿qué tipo de empresa crees que es?', 'Escriban las respuestas y los ajustes en las notas.']::text[], 'Ruta elegida y 3 respuestas anotadas.', 'Hay ruta elegida y lista de ajustes.', 13),
  ('T11', 'f1', 'MJ', 2, false, 'Constituir la SAS en la VUE', 'La CCB indica que en Bogotá la SAS virtual se tramita por la Ventanilla Única Empresarial.', array['Entra a vue.gov.co y crea el usuario de cada socia.', 'Diligencia la constitución con los datos acordados.', 'Elige CIIU y régimen en el RUT: 05 (ordinario) o 47 (Simple), según el contador.', 'Adjunta los documentos pedidos.', 'Firma con la firma electrónica que suministra la CCB.', 'Paga matrícula, formulario RUES e impuesto de registro.', 'Guarda el número de radicado.']::text[], 'Radicado de constitución.', 'Trámite radicado y pagado.', 14),
  ('T16', 'f1', 'MJ', 2, false, 'Política de tratamiento de datos y aviso de privacidad', 'La web, el chatbot y el CRM recogen datos personales (Ley 1581 de 2012).', array['Responsable: Imperium Lab S.A.S., con datos de contacto.', 'Finalidades: contacto comercial, prestación de servicios y facturación.', 'Derechos de los titulares y canal de consultas y reclamos (correo).', 'Texto de autorización para formularios y chatbot, con casilla sin marcar por defecto.', 'Aviso de privacidad corto para la web.', 'Nota: el RNBD solo es obligatorio con activos superiores a 100.000 UVT, según la SIC.', 'Guarda la versión con fecha. Recomendado: revisión de un abogado.']::text[], 'Política y aviso de privacidad v1.', 'Textos listos para la web y los contratos.', 15),
  ('T12', 'f1', 'MJ', 1, false, 'Seguimiento: matrícula, NIT y certificado', 'Sin certificado y RUT no se abre cuenta ni se factura. Los tiempos dependen de la CCB.', array['Revisa el estado del trámite cada dos días.', 'Si hay devolución, corrige y vuelve a radicar.', 'Descarga el certificado de existencia y representación legal.', 'Descarga el RUT con el NIT.', 'Guarda todo en la carpeta Legal compartida.']::text[], 'Certificado y RUT en la carpeta Legal.', 'La SAS tiene NIT.', 16),
  ('T13', 'f1', 'MJ', 2, false, 'Abrir la cuenta bancaria de la empresa', 'Los pagos de clientes y la pasarela deben llegar a nombre de la SAS.', array['Compara 2 o 3 bancos: cuota de manejo, costo de transferencias, banca en línea con dos usuarios y compatibilidad con la pasarela elegida.', 'Reúne certificado de existencia, RUT y cédula de la representante legal.', 'Abre la cuenta y activa el token o la app.', 'Actualiza los datos bancarios en el contrato modelo y en la propuesta.']::text[], 'Cuenta bancaria activa.', 'Se puede recibir una transferencia a nombre de la SAS.', 17),
  ('T14', 'f1', 'MJ', 4, true, 'Habilitarse como facturador electrónico y emitir la primera factura', 'Es la puerta de la Fase 1: con esto la empresa ya opera formalmente.', array['Elige la solución: la gratuita de la DIAN o un software de facturación (o Odoo, si lo eligieron como CRM).', 'Regístrate como facturador electrónico en los servicios en línea de la DIAN.', 'Tramita el certificado de firma digital (gratuito con la solución de la DIAN).', 'Haz el set de pruebas de habilitación. En la solución gratuita: 2 facturas, 1 nota débito y 1 nota crédito.', 'Solicita la numeración autorizada.', 'Configura NIT, régimen, CIIU y resolución en la herramienta.', 'Emite la primera factura real, por ejemplo el próximo pago de un cliente.']::text[], 'Primera factura electrónica emitida.', 'La DIAN validó la primera factura.', 18),
  ('T24', 'f2', 'JQ', 4, false, 'Logo final y sistema de versiones', 'Un logo útil viene con sus versiones y reglas, no como una sola imagen.', array['Vectoriza en un SVG limpio, con formas cerradas.', 'Versiones: horizontal, vertical y solo símbolo.', 'Variantes: positivo, negativo, monocromo negro y monocromo blanco.', 'Define el área de respeto (por ejemplo, la altura de la «I») y el tamaño mínimo en px y en mm.', 'Favicon 32×32, ícono 180×180 y avatar 1080×1080 para redes.', 'Exporta SVG, PNG @1x y @2x y PDF.', 'Ordena la carpeta Marca/Logo con nombres claros.']::text[], 'Paquete de logo completo.', 'MJ puede usar el logo en la web sin pedir ningún archivo.', 19),
  ('T15', 'f1', 'MJ', 1, false, 'Inscripción en ICA Bogotá (RIT)', 'El ICA es un impuesto distrital. No pudimos verificar el proceso ni la tarifa: hay que confirmarlo.', array['Confirma con el contador si la inscripción en el RIT quedó hecha con la matrícula o si se hace aparte.', 'Revisa el proceso en haciendabogota.gov.co.', 'Confirma la tarifa según el CIIU.', 'Pasa las fechas de declaración a Google Calendar.']::text[], 'Inscripción confirmada y fechas en el calendario.', 'Saben cuándo y cuánto declarar.', 20),
  ('T25', 'f2', 'JQ', 2, false, 'Paleta y tipografía accesibles', 'Si venden webs que cumplen WCAG, su propia marca también debe cumplir.', array['Conserva la regla 60-30-10 del manual.', 'Botón naranja de acción con texto #0D0D12 (6,84:1) en lugar de blanco (2,84:1).', 'Violeta para texto sobre blanco: un tono más oscuro, tipo #6A4BF0 (5,42:1).', 'Violeta sobre fondo oscuro: un tono claro, tipo #9D86FF (6,73:1).', 'Turquesa y azul solo como decoración o con texto oscuro.', 'Elige 2 familias con nombre en Google Fonts: una para títulos y otra para texto.', 'Escribe los tokens de color (nombre, hex y uso) para la web.']::text[], 'Tabla de color y tipografías definidas.', 'Cada combinación de texto y fondo da al menos 4,5:1.', 21),
  ('T17', 'f1', 'MJ', 2, false, 'Contrato modelo a nombre de la SAS', 'Los contratos nuevos deben quedar a nombre de la empresa, no de una socia.', array['Parte del contrato de Estancoficial.', 'Cambia EL DESARROLLADOR por IMPERIUM LAB S.A.S., con NIT y representante legal.', 'Ajusta el IVA según el régimen elegido.', 'Agrega el Acta de calidad como anexo.', 'Actualiza la cláusula de datos personales con la política nueva.', 'Pon la cuenta bancaria nueva.', 'Recomendado: revisión de un abogado.']::text[], 'Contrato modelo v2.', 'Listo para el próximo cliente.', 22),
  ('T18', 'f1', 'MJ', 2, false, 'Radicar la marca ante la SIC', 'Protege el nombre en Colombia. La marca nominativa (solo palabras) no necesita el logo final.', array['Radica primero la marca nominativa «IMPERIUM LAB».', 'Clase 42 como base. Evalúen 9 y 35 (cada clase adicional cuesta más).', 'Revisen si califican al programa PI-e (hasta 85% de descuento con certificado del CIGEPI) o a la tarifa MiPyme: COP 970.500 la primera clase en línea, frente a COP 1.348.500 la general.', 'Radica en línea a nombre de la SAS.', 'Guarda el radicado.', 'Pon en el calendario la publicación en la Gaceta: hay 30 días hábiles para oposiciones.']::text[], 'Radicado de solicitud de marca.', 'Solicitud pagada y radicada.', 23),
  ('T26', 'f2', 'JQ', 4, false, 'Manual v2: propuesta de valor e identidad (módulos 1 y 2)', 'El manual es la referencia para la web, las redes y las propuestas.', array['Reemplaza nombre y dominio en todo el documento.', 'Reescribe misión, promesa y pitch de 15 segundos con el brief.', 'Reescribe el pilar 2: de «herramientas no-code» a «hecho con estándares verificables (Acta de calidad)».', 'Ajusta el posicionamiento al precio decidido.', 'Actualiza el significado del logo según la ruta elegida.', 'Actualiza la paleta con las reglas de contraste y nombra las tipografías.', 'Revisa los eslóganes frente a la promesa nueva.', 'Marca la versión como v2 con fecha.']::text[], 'Manual v2, módulos 1 y 2.', 'No queda ninguna mención a Imperial Tech ni a no-code.', 24),
  ('T30', 'f3', 'MJ', 2, false, 'Elegir CRM y herramienta de automatización', 'El CRM es la base de la operación. Elegirlo bien evita migrar después.', array['Requisitos mínimos: leads, pipeline, propuestas, proyectos, tickets y facturación.', 'Opción A, Odoo: CRM, proyectos y facturación DIAN en uno. La API externa solo está en el plan Custom.', 'Opción B, HubSpot Free (2 usuarios y 1.000 contactos) más un software de facturación.', 'Automatizador: n8n Cloud Starter (EUR 20 al mes) o Make.', 'Prueba cada opción 30 minutos con un caso real (un lead de Estancoficial).', 'Decide y anota la razón en las notas.']::text[], 'Decisión de CRM y automatizador.', 'Hay cuenta creada en la herramienta elegida.', 25),
  ('T31', 'f3', 'MJ', 4, false, 'Configurar el CRM', 'Todo cliente y prospecto vive en un solo lugar.', array['Crea las etapas: Prospecto → Contactado → Respondió → Reunión → Diagnóstico pagado → Propuesta → Ganado / Perdido.', 'Crea los campos: vertical, fuente (frío, referido, alianza, redes, web), ciudad, tamaño, web actual y puntaje de PageSpeed.', 'Carga los clientes actuales (Estancoficial, SODO) y las oportunidades abiertas.', 'Crea las plantillas de correo.', 'Crea usuarios para las dos con verificación en dos pasos.', 'Arma la vista «mis tareas de hoy».']::text[], 'CRM configurado con datos reales.', 'Las dos pueden registrar un lead en menos de un minuto.', 26),
  ('T27', 'f2', 'JQ', 4, false, 'Manual v2: uso del logo, aplicaciones y componentes web', 'Son las secciones que faltan hoy en el manual.', array['Usos correctos e incorrectos del logo: no estirar, no cambiar colores, no poner sombras, no usar sobre fondos con poco contraste.', 'Área de respeto y tamaño mínimo.', 'Iconografía: estilo y grosor de línea.', 'Fotografía: personas y negocios reales, sin stock genérico.', 'Componentes web: botón primario violeta, botón de acción naranja, formularios y estados (foco visible, error, éxito).', 'Plantillas de redes: post, historia y carrusel.', 'Voz y tono con ejemplos de frases que sí y que no.']::text[], 'Manual v2 completo.', 'Alguien externo podría hacer un post sin preguntar nada.', 27),
  ('T28', 'f2', 'JQ', 4, false, 'Aplicaciones: propuesta, contrato, Acta de calidad y firma de correo', 'Son las piezas que el cliente ve en cada venta.', array['Plantilla de propuesta: 1 página más un anexo de precios.', 'Diseño del contrato con la marca (con el texto actualizado por MJ).', 'Acta de calidad: checklist de entrega con Core Web Vitals, WCAG 2.2 AA, SEO técnico, seguridad, datos personales y propiedad.', 'Firma de correo de Gmail para las dos.', 'Avatar y portada para las cuatro redes.', 'Tarjeta digital con QR a imperiumlab.co.']::text[], 'Kit de aplicaciones.', 'La próxima propuesta sale con la marca nueva.', 28),
  ('T29', 'f2', 'AMBAS', 1, true, 'Aprobar el manual de marca v2', 'Es la puerta de la Fase 2. Sin manual aprobado no se diseña la web.', array['Lean el manual completo.', 'Revisen: nombre y dominio correctos en todo el documento.', 'Revisen: todas las combinaciones de color dan al menos 4,5:1.', 'Revisen: el logo se lee a 16 px.', 'Aprueben la versión y guarden el PDF en la carpeta compartida.', 'Cambien las fotos de perfil en las redes.']::text[], 'Manual v2 aprobado en PDF.', 'Versión firmada por las dos.', 29),
  ('T42', 'f4', 'MJ', 1, false, 'Preparar el buzón para prospección', 'Un buzón nuevo que envía mucho de golpe termina en spam.', array['Confirma SPF, DKIM y DMARC en PASS.', 'Configura Google Postmaster Tools para el dominio. La tasa de spam debe quedar por debajo de 0,30%.', 'Empieza con pocos envíos diarios y sube de a poco. Lemlist sugiere menos de 50 por día por buzón.', 'Firma con datos de contacto y una forma clara de no recibir más correos.', 'Carga las plantillas en el CRM.']::text[], 'Buzón listo para enviar.', 'Un correo de prueba llega a la bandeja principal de Gmail.', 30),
  ('T47', 'f4', 'MJ', 2, false, 'Mapa de aliados y primer contacto', 'En la encuesta de SparkToro los referidos son la principal fuente de clientes de las agencias.', array['Lista 10 aliados posibles: contadores de pymes, agencias de marketing sin equipo técnico, proveedores de software (EFI/Effichat) y comunidades de emprendimiento.', 'Revisa la Ruta Bogotá Cundinamarca Emprende de la CCB.', 'Define una propuesta simple de referidos (comisión o intercambio).', 'Escribe el mensaje de contacto.', 'Registra a cada aliado en el CRM con fuente «Alianza».']::text[], '10 aliados en el CRM y mensaje listo.', 'Al menos 3 aliados contactados.', 31),
  ('T40', 'f4', 'MJ', 4, false, 'Mapear 50 prospectos de la vertical', 'Lista corta y bien filtrada: es la base de la prospección con valor.', array['Con la matrícula al día, averigua en la CCB cómo pedir la base de datos de empresas del RUES filtrada por CIIU de la vertical, Bogotá y rango de ingresos.', 'Revisa los candidatos uno a uno en Google Maps. No uses extractores masivos: los términos de Google lo prohíben.', 'Para cada uno anota: web (sí o no, y puntaje en PageSpeed), WhatsApp (manual o automatizado), decisor en LinkedIn y correo corporativo.', 'Carga cada uno en el CRM en la etapa Prospecto, con su fuente.', 'Clasifícalos en A, B o C según el ICP.']::text[], '50 prospectos en el CRM.', 'Hay al menos 30 prospectos A o B.', 32),
  ('T37', 'f3', 'MJ', 3, false, 'Kit de verificación del Acta de calidad', 'El Acta se vende como garantía: necesitan una forma rápida y repetible de medirla en cada proyecto.', array['Rendimiento: PageSpeed Insights o Lighthouse en modo celular. Umbrales: LCP ≤ 2,5 s y CLS ≤ 0,1.', 'Accesibilidad: Lighthouse más una extensión como axe DevTools, y revisión manual con teclado y lector de pantalla.', 'SEO técnico: prueba de resultados enriquecidos de Google y revisión de sitemap, títulos y descripciones.', 'Seguridad: revisión de cabeceras HTTP (HSTS, CSP, nosniff, Referrer-Policy).', 'Plantilla del informe: una fila por criterio con resultado, evidencia y fecha.', 'Prueba el kit con la web de Estancoficial y guarda el resultado como ejemplo.']::text[], 'Kit de verificación y plantilla de informe.', 'Medir una web completa toma menos de 1 hora.', 33),
  ('T41', 'f4', 'JQ', 3, false, 'Guiones: video diagnóstico, 4 correos y mensaje de LinkedIn', 'El primer contacto debe dar valor antes de pedir algo.', array['Guion del video de 2 minutos: saludo con nombre, 3 hallazgos concretos de su web o WhatsApp, 1 idea y la invitación a 15 minutos.', 'Correo 1 (día 1) con el video: 50 a 150 palabras y un solo llamado a la acción.', 'Correos de los días 3, 7 y 12: seguimiento, caso y cierre amable.', 'Mensaje de conexión para LinkedIn.', 'Prueba las estructuras PAS y AIDA.', 'Incluye siempre una forma visible de no recibir más mensajes.', 'Ley 2300: lunes a viernes de 7 a.m. a 7 p.m. y sábados de 8 a.m. a 3 p.m., un contacto al día y sin varios canales la misma semana.', 'No escribas en frío por WhatsApp: la política de Meta pide consentimiento previo.']::text[], 'Guiones y plantillas listos.', 'MJ puede cargar las plantillas en el CRM.', 34),
  ('T32', 'f3', 'JQ', 4, false, 'Mapa del sitio y textos de imperiumlab.co', 'La web es la vitrina y la primera prueba del Acta de calidad.', array['Páginas: Inicio, Servicios (3 paquetes), Diagnóstico, Acta de calidad, Casos, Nosotras, Contacto y Política de datos.', 'Inicio: promesa, prueba (caso), cómo trabajamos (4 semanas) y botón naranja «Agenda tu diagnóstico».', 'Textos con el tono del manual.', 'SEO: título y descripción por página, y una palabra clave principal por página.', 'Preguntas frecuentes.']::text[], 'Mapa del sitio y textos completos.', 'Textos aprobados por MJ.', 35),
  ('T49', 'f4', 'MJ', 2, false, 'Tablero del embudo en el CRM', 'Sin números no se sabe qué canal vale la pena.', array['Métricas por canal: prospectos, contactados, % de respuesta, % de respuestas positivas, reuniones, propuestas y cierres.', 'Ticket promedio por paquete.', 'CAC = (costos de ventas y marketing + horas valoradas) / clientes nuevos.', 'Relación LTV:CAC: HubSpot sugiere 3 o más.', 'Referencia de respuesta en frío: Close cita 5% a 15%. Ajusten la meta propia con el primer lote.']::text[], 'Tablero del embudo.', 'El tablero se actualiza solo con los datos del CRM.', 36),
  ('T36a', 'f3', 'MJ', 4, false, 'Automatizar propuesta, contrato y anticipo', 'Dos personas atienden más clientes si los pasos repetidos se hacen solos.', array['Propuesta generada desde la plantilla con los datos del CRM.', 'Al aceptarse la propuesta, el contrato sale a firma electrónica.', 'Al firmarse, se emite la factura del anticipo y se envía el link de pago.', 'El pago confirmado cambia la etapa a Ganado.', 'Documenta cada flujo: qué lo dispara, qué hace y quién lo revisa.', 'Licencia de n8n: se pueden construir flujos para clientes y cobrar por ellos, pero no revender n8n con marca propia.']::text[], 'Flujo propuesta → contrato → anticipo funcionando.', 'Una prueba completa con un cliente ficticio pasa sin intervención.', 37),
  ('T33', 'f3', 'JQ', 6, false, 'Diseño de la web en Figma', 'Diseñar antes de programar evita rehacer código.', array['Wireframes pensando primero en celular.', 'Interfaz con los tokens del manual v2.', 'Componentes reutilizables.', 'Estados de foco y de error.', 'Prueba de contraste de cada combinación.', 'Revisión con MJ y versión final.']::text[], 'Diseño final en Figma.', 'Todas las páginas diseñadas en celular y escritorio.', 38),
  ('T43a1', 'f4', 'JQ', 4, false, 'Lote 1: grabar 10 videos diagnóstico', 'Cada video personalizado diferencia el primer contacto del spam.', array['Elige 10 prospectos A del CRM.', 'Corre PageSpeed y revisa el WhatsApp de cada uno.', 'Graba un video de 2 minutos por prospecto (Loom o similar).', 'Pega el enlace del video en el CRM.']::text[], '10 videos enlazados en el CRM.', 'MJ puede enviar el lote.', 39),
  ('T43b1', 'f4', 'MJ', 2, false, 'Lote 1: enviar la secuencia y registrar respuestas', 'El seguimiento es donde llega la mayoría de respuestas.', array['Envía el correo 1 con el video, dentro del horario de la Ley 2300.', 'Programa en el CRM los recordatorios de los días 3, 7 y 12.', 'Registra cada respuesta y mueve la etapa.', 'Agenda reunión con quien responda.', 'Anota enviados, respuestas, respuestas positivas y reuniones.']::text[], 'Lote 1 enviado y medido.', 'Los 10 tienen estado actualizado en el CRM.', 40),
  ('T38', 'f3', 'JQ', 1, false, 'Perfil de empresa en Google', 'Aparecer en Google cuando busquen la marca.', array['Créalo como empresa de servicios con la dirección oculta. Google no permite oficinas virtuales.', 'Nombre exacto, sin palabras clave agregadas.', 'Categorías, horario, logo y portada.', 'Enlace a imperiumlab.co.', 'Pide la primera reseña a Estancoficial.']::text[], 'Perfil verificado.', 'El perfil aparece al buscar Imperium Lab.', 41),
  ('T34a', 'f3', 'JQ', 6, false, 'Maquetar la web (frontend)', 'Aquí se cumple lo que promete el diferenciador.', array['Framework estático (Astro o Next.js) y repositorio en GitHub.', 'HTML semántico: header, nav, main y footer, con un solo h1 por página.', 'Imágenes optimizadas (WebP o AVIF) con ancho y alto definidos para evitar saltos (CLS).', 'Fuentes con font-display: swap.', 'Accesibilidad: textos alternativos, etiquetas en formularios, foco visible y navegación con teclado.', 'Datos estructurados JSON-LD (Organization y Service).']::text[], 'Web maquetada en un entorno de prueba.', 'Funciona con teclado y en celular.', 42),
  ('T34b', 'f3', 'MJ', 6, false, 'Integraciones: formulario, CRM y pago del diagnóstico', 'Cada visita interesada debe terminar como lead en el CRM.', array['Formulario de contacto con casilla de autorización de datos → webhook de n8n → lead en el CRM → respuesta automática desde hola@.', 'Botón de pago del diagnóstico con la pasarela. Referencia: Wompi 2,65% + COP 700 + IVA; Bold 2,99% + COP 900.', 'Webhook de pago aprobado → etapa «Diagnóstico pagado».', 'Analítica con aviso de privacidad.', 'Prueba de punta a punta con un pago real de bajo valor.']::text[], 'Formulario y pago conectados al CRM.', 'Un lead de prueba y un pago de prueba llegan al CRM.', 43),
  ('T39', 'f3', 'MJ', 2, false, 'Publicar imperiumlab.co', 'Pasar de la prueba al dominio real con seguridad.', array['Hosting estático (por ejemplo Vercel, Netlify o Cloudflare Pages).', 'Conecta el dominio y activa HTTPS.', 'Cabeceras de seguridad: HSTS, CSP, X-Content-Type-Options: nosniff y Referrer-Policy.', 'Si tienen soyimperialtech.com, redirígelo con 301 a imperiumlab.co.', 'Verifica el dominio en Google Search Console y envía el sitemap.', 'Publica la política de datos.']::text[], 'imperiumlab.co en línea.', 'La web carga con HTTPS y aparece en Search Console.', 44),
  ('T35', 'f3', 'AMBAS', 2, true, 'Pasar el Acta de calidad a imperiumlab.co', 'Es la puerta de la Fase 3 y el primer caso real del Acta.', array['PageSpeed en celular: LCP ≤ 2,5 s y CLS ≤ 0,1. El INP se mide con datos reales de visitas.', 'WCAG 2.2 AA: teclado, lector de pantalla (NVDA o VoiceOver), contraste y tamaño de botones.', 'Prueba de resultados enriquecidos de Google.', 'Cabeceras de seguridad revisadas.', 'Formularios con autorización de datos.', 'Corrige lo que falle y guarda las evidencias.']::text[], 'Acta de calidad firmada para imperiumlab.co.', 'Todos los puntos del Acta en verde.', 45),
  ('T44', 'f4', 'JQ', 2, false, 'Calendario de contenido de 4 semanas', 'Con 2 horas al día, la constancia depende de planear antes.', array['Pilares: antes y después con PageSpeed, demo del chatbot en 30 segundos, educativo sobre el Acta de calidad, detrás de cámaras y casos.', 'Referencia de Hootsuite: Instagram y TikTok de 3 a 5 veces por semana.', 'Empiecen con 3 publicaciones por semana y reutilicen el mismo video vertical en Reels y TikTok.', 'Reels de menos de 90 segundos con gancho en los primeros 3 segundos.', 'Facebook principalmente para anuncios.', 'Arma la tabla semana por semana con tema, formato y fecha.']::text[], 'Calendario de 4 semanas.', 'Cada semana tiene 3 piezas definidas.', 46),
  ('T46', 'f4', 'JQ', 2, false, 'Caso de éxito Estancoficial', 'El primer caso es la mejor prueba de venta.', array['Pide autorización escrita al cliente.', 'Reúne el antes y el después: capturas, tiempos de respuesta y pedidos por chatbot, si hay datos.', 'Pide una frase del cliente.', 'Formatos: página en la web, carrusel y PDF de 1 página.', 'No publiques cifras que el cliente no haya aprobado.']::text[], 'Caso en 3 formatos.', 'El cliente aprobó el texto.', 47),
  ('T45a', 'f4', 'JQ', 4, false, 'Producir el lote 1 de contenido (6 piezas)', 'Producir en lote ahorra tiempo frente a hacer una pieza por día.', array['Graba 3 videos verticales (sirven para Reels y TikTok).', 'Diseña 3 carruseles con las plantillas del manual.', 'Escribe los textos y llamados a la acción.', 'Programa las publicaciones en Meta Business Suite y TikTok.', 'Anota la línea base de cada cuenta (seguidores y alcance).']::text[], '6 piezas programadas.', 'Hay contenido para 2 semanas.', 48),
  ('T36b', 'f3', 'MJ', 4, false, 'Automatizar onboarding, soporte y reseñas', 'Completa el recorrido del cliente: el último paso trae al siguiente.', array['Pago confirmado → correo de bienvenida, formulario de accesos y proyecto con tareas desde una plantilla.', 'Aviso semanal de avance al cliente.', 'Soporte: correo o WhatsApp → ticket registrado.', 'Entre 7 y 14 días después del cierre: pedir reseña en Google y un referido.', 'Documenta cada flujo.']::text[], 'Recorrido del cliente automatizado.', 'Una prueba de punta a punta pasa sin intervención.', 49),
  ('T43a2', 'f4', 'JQ', 4, false, 'Lote 2: grabar 10 videos diagnóstico', 'Segundo lote, ajustado con lo que respondió el primero.', array['Revisa qué funcionó en el lote 1 (asunto, duración del video, hallazgos).', 'Elige 10 prospectos A o B nuevos.', 'Corre PageSpeed y revisa su WhatsApp.', 'Graba los 10 videos y enlázalos en el CRM.']::text[], '10 videos enlazados en el CRM.', 'MJ puede enviar el lote.', 50),
  ('T43b2', 'f4', 'MJ', 2, false, 'Lote 2: enviar la secuencia y registrar respuestas', 'Mantener el ritmo de prospección.', array['Envía el correo 1 dentro del horario permitido.', 'Programa los recordatorios de los días 3, 7 y 12.', 'Registra respuestas y mueve etapas.', 'Compara las métricas con el lote 1.']::text[], 'Lote 2 enviado y medido.', 'Los 10 tienen estado actualizado.', 51),
  ('T45b', 'f4', 'JQ', 4, false, 'Producir el lote 2 de contenido (6 piezas)', 'Dos semanas más de contenido, con lo aprendido del lote 1.', array['Revisa las métricas del lote 1: reproducciones, guardados y mensajes.', 'Repite el formato que mejor funcionó.', 'Graba 3 videos y diseña 3 carruseles.', 'Programa las publicaciones.']::text[], '6 piezas programadas.', 'Hay contenido para 2 semanas más.', 52),
  ('T48', 'f4', 'JQ', 2, false, 'Piloto de anuncios clic a WhatsApp', 'Es el mismo servicio que venden a SODO: usarlo en casa también lo demuestra.', array['Definan juntas el presupuesto de prueba.', 'Requisito: página de Facebook con WhatsApp Business vinculado.', 'Un anuncio con el mejor reel del lote 1.', 'Segmentación: Bogotá e intereses de la vertical.', 'Mensaje automático de bienvenida.', 'Midan 2 semanas: costo por conversación y conversaciones que pasan a reunión.', 'Quien llega por estos anuncios abre una ventana gratuita de 72 horas de mensajes, según Meta.']::text[], 'Campaña piloto activa.', 'Hay datos de 2 semanas.', 53),
  ('T43a3', 'f4', 'JQ', 4, false, 'Lote 3: grabar 10 videos diagnóstico', 'Tercer lote para tener datos comparables.', array['Ajusta el guion con lo aprendido.', 'Elige 10 prospectos nuevos.', 'Graba los 10 videos y enlázalos en el CRM.']::text[], '10 videos enlazados.', 'MJ puede enviar el lote.', 54),
  ('T43b3', 'f4', 'MJ', 2, false, 'Lote 3: enviar la secuencia y registrar respuestas', 'Cierra la primera ronda de prospección.', array['Envía el correo 1 dentro del horario permitido.', 'Programa los recordatorios.', 'Registra respuestas y mueve etapas.', 'Actualiza el tablero del embudo.']::text[], 'Lote 3 enviado y medido.', '30 prospectos contactados en total.', 55),
  ('T50', 'f4', 'AMBAS', 1, true, 'Revisión del embudo y plan de las siguientes 4 semanas', 'Decidir con datos qué se repite y qué se deja.', array['Revisen las métricas por canal: frío, referidos, alianzas, redes y anuncios.', 'Definan qué canal recibe más horas.', 'Ajusten mensajes, vertical o precios si hace falta.', 'Escriban el plan de las siguientes 4 semanas.']::text[], 'Plan de las siguientes 4 semanas.', 'Hay plan nuevo acordado.', 56)
on conflict (id) do update set fase_id = excluded.fase_id, responsable = excluded.responsable, horas = excluded.horas, es_hito = excluded.es_hito, titulo = excluded.titulo, porque = excluded.porque, pasos = excluded.pasos, entregable = excluded.entregable, criterio_hecho = excluded.criterio_hecho, orden = excluded.orden;

delete from public.tarea_dependencias;
insert into public.tarea_dependencias (tarea_id, depende_de) values
  ('T05', 'T04'),
  ('T05', 'T06'),
  ('T07', 'T01'),
  ('T07', 'T04'),
  ('T07', 'T06'),
  ('T07', 'T05'),
  ('T08', 'T07'),
  ('T21', 'T07'),
  ('T21', 'T20'),
  ('T09', 'T08'),
  ('T22', 'T21'),
  ('T22', 'T01'),
  ('T10', 'T09'),
  ('T23', 'T22'),
  ('T11', 'T10'),
  ('T11', 'T01'),
  ('T12', 'T11'),
  ('T13', 'T12'),
  ('T14', 'T12'),
  ('T24', 'T23'),
  ('T15', 'T12'),
  ('T25', 'T23'),
  ('T17', 'T12'),
  ('T17', 'T16'),
  ('T18', 'T12'),
  ('T18', 'T01'),
  ('T26', 'T21'),
  ('T26', 'T25'),
  ('T30', 'T07'),
  ('T31', 'T30'),
  ('T27', 'T24'),
  ('T27', 'T25'),
  ('T28', 'T27'),
  ('T29', 'T26'),
  ('T29', 'T28'),
  ('T42', 'T03'),
  ('T47', 'T04'),
  ('T40', 'T31'),
  ('T40', 'T12'),
  ('T40', 'T04'),
  ('T37', 'T28'),
  ('T41', 'T05'),
  ('T41', 'T21'),
  ('T32', 'T26'),
  ('T32', 'T05'),
  ('T49', 'T31'),
  ('T36a', 'T31'),
  ('T36a', 'T28'),
  ('T33', 'T32'),
  ('T33', 'T29'),
  ('T43a1', 'T40'),
  ('T43a1', 'T41'),
  ('T43b1', 'T43a1'),
  ('T43b1', 'T42'),
  ('T38', 'T29'),
  ('T34a', 'T33'),
  ('T34b', 'T33'),
  ('T34b', 'T31'),
  ('T34b', 'T13'),
  ('T39', 'T34a'),
  ('T39', 'T34b'),
  ('T39', 'T16'),
  ('T35', 'T39'),
  ('T44', 'T21'),
  ('T46', 'T24'),
  ('T45a', 'T44'),
  ('T45a', 'T24'),
  ('T36b', 'T34b'),
  ('T43a2', 'T43b1'),
  ('T43b2', 'T43a2'),
  ('T45b', 'T45a'),
  ('T48', 'T45a'),
  ('T48', 'T39'),
  ('T43a3', 'T43b2'),
  ('T43b3', 'T43a3'),
  ('T50', 'T43b3'),
  ('T50', 'T49'),
  ('T50', 'T48');

delete from public.tarea_fuentes;
insert into public.tarea_fuentes (tarea_id, fuente_clave, orden) values
  ('T01', 'sicMarcas', 0),
  ('T01', 'sicTarifas', 1),
  ('T01', 'rues', 2),
  ('T01', 'imperiumlabs', 3),
  ('T20', 'ixdf', 0),
  ('T20', 'wcag', 1),
  ('T03', 'gSender', 0),
  ('T04', 'hubspotIcp', 0),
  ('T05', 'enns', 0),
  ('T05', 'dyf', 1),
  ('T05', 'verjel', 2),
  ('T05', 'pivoti', 3),
  ('T05', 'clutch', 4),
  ('T07', 'plan', 0),
  ('T08', 'dianRst', 0),
  ('T08', 'dian977', 1),
  ('T08', 'dianCiiu', 2),
  ('T08', 'ccbLey1780', 3),
  ('T21', 'wheeler', 0),
  ('T09', 'ley1258', 0),
  ('T09', 'rm01', 1),
  ('T09', 'sasVirtual', 2),
  ('T22', 'wheeler', 0),
  ('T11', 'vue', 0),
  ('T11', 'sasVirtual', 1),
  ('T11', 'ccbTarifas', 2),
  ('T16', 'rnbd', 0),
  ('T16', 'sicCorp', 1),
  ('T12', 'sasVirtual', 0),
  ('T14', 'dianFe', 0),
  ('T25', 'wcag', 0),
  ('T18', 'sicMarcas', 0),
  ('T18', 'sicTarifas', 1),
  ('T26', 'ixdf', 0),
  ('T30', 'odoo', 0),
  ('T30', 'odooCo', 1),
  ('T30', 'hubspot', 2),
  ('T30', 'n8n', 3),
  ('T30', 'make', 4),
  ('T27', 'ixdf', 0),
  ('T28', 'vitals', 0),
  ('T28', 'wcag', 1),
  ('T42', 'gSender', 0),
  ('T42', 'lemlist', 1),
  ('T47', 'sparktoro', 0),
  ('T47', 'effichat', 1),
  ('T47', 'ruta', 2),
  ('T40', 'ruesDb', 0),
  ('T40', 'mapsTos', 1),
  ('T40', 'sicCorp', 2),
  ('T37', 'vitals', 0),
  ('T37', 'wcag', 1),
  ('T37', 'gSchema', 2),
  ('T37', 'owaspH', 3),
  ('T41', 'close', 0),
  ('T41', 'saleshandy', 1),
  ('T41', 'ross', 2),
  ('T41', 'ley2300', 3),
  ('T41', 'waPolicy', 4),
  ('T32', 'gAi', 0),
  ('T49', 'hubspotCac', 0),
  ('T49', 'close', 1),
  ('T36a', 'n8n', 0),
  ('T36a', 'n8nLic', 1),
  ('T33', 'wcag', 0),
  ('T43a1', 'vitals', 0),
  ('T43b1', 'ley2300', 0),
  ('T38', 'gbp', 0),
  ('T34a', 'vitals', 0),
  ('T34a', 'wcag', 1),
  ('T34a', 'gSchema', 2),
  ('T34b', 'wompi', 0),
  ('T34b', 'bold', 1),
  ('T34b', 'n8n', 2),
  ('T39', 'owaspH', 0),
  ('T39', 'owasp10', 1),
  ('T39', 'gSitemap', 2),
  ('T35', 'vitals', 0),
  ('T35', 'wcag', 1),
  ('T35', 'gSchema', 2),
  ('T35', 'owaspH', 3),
  ('T44', 'hootsuite', 0),
  ('T44', 'hootIg', 1),
  ('T45a', 'hootIg', 0),
  ('T36b', 'n8n', 0),
  ('T43b2', 'ley2300', 0),
  ('T48', 'ctwa', 0),
  ('T48', 'waPricing', 1),
  ('T50', 'sparktoro', 0);

insert into public.personas (codigo, nombre, rol) values
  ('MJ', 'MJ', 'Datos, legal y plataforma'),
  ('JQ', 'JQ', 'Marca, producto y clientes')
on conflict (codigo) do nothing;

insert into public.plan_config (id, fecha_inicio, horas_por_dia, festivos, replanificar) values
  (1, '2026-10-09', 2, array['2026-10-12', '2026-11-02', '2026-11-16', '2026-12-08', '2026-12-25', '2027-01-01', '2027-01-11']::date[], false)
on conflict (id) do nothing;

commit;
